# Generated by Django 3.1.5 on 2021-01-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_remove_item_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeitem',
            old_name='accepted',
            new_name='responded',
        ),
    ]
