# Generated by Django 3.1.5 on 2021-01-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_auto_20210118_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
