# Generated by Django 3.1.5 on 2021-01-23 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0011_auto_20210123_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitor', to=settings.AUTH_USER_MODEL),
        ),
    ]
