# Generated by Django 3.1.5 on 2021-01-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210111_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
