# Generated by Django 3.0.5 on 2020-12-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_auto_20201209_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('B', 'Bestseller'), ('S', 'Special Deal')], max_length=1, null=True),
        ),
    ]
