# Generated by Django 3.0.5 on 2020-12-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_auto_20201214_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], default='N', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CL', 'Clothing'), ('ED', 'Electronics & Devices'), ('KD', 'Kids'), ('FI', 'Food Items'), ('KI', 'Kitchen'), ('FH', 'Furniture & Housing')], default='CL', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='blah', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=models.ImageField(default='C:/Users/Dell  PC/Desktop/Pins/8abbebc63f9c626d35f83823a0c92514', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default='example', max_length=100),
            preserve_default=False,
        ),
    ]
