# Generated by Django 3.0.5 on 2020-12-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_auto_20201212_1542'),
        ('base_app', '0006_auto_20201214_1415'),
    ]

    operations = [
    ]
