# Generated by Django 3.0.5 on 2020-12-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_merge_20201215_0436'),
        ('base_app', '0007_merge_20201215_1200'),
    ]

    operations = [
    ]
