# Generated by Django 3.0.5 on 2020-12-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_item_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
